<?php

namespace Sonata\MediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MediaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\MediaBundle\Controller\MediaController();
        return $instance;
    }
}
